server:
  port: 8088
spring:
  # 配置国际化
  messages:
    basename: i18n.login
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/perseverestudy?useUnicode=true&characterEncoding=utf8
      username: root
      password: root
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true
#  thymeleaf:
#    cache: false
#    mode: LEGACYHTML5
#    prefix: classpath:/static/front-end/MicFamily-login/
#    suffix: .html

#SavePath:
#  ProfilePhoto: '
#  ProfilePhotoMapper: '/profilePhoto/' #图标的映射路径

mybatis-plus:
  type-aliases-package:
  mapper-locations:
  global-config:
    db-config:
      id-type: auto

#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
